# Generated by Django 3.0.6 on 2020-06-29 16:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('s1app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gall',
            name='category',
        ),
        migrations.AddField(
            model_name='gall',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
