# Generated by Django 3.0.6 on 2020-06-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s1app', '0002_auto_20200630_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gall',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
