# Generated by Django 3.0.6 on 2020-07-05 22:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('s1app', '0003_auto_20200630_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='gall',
            name='date',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gall',
            name='summ',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
