# Generated by Django 3.0.6 on 2020-07-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s1app', '0004_auto_20200706_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gall',
            name='date',
            field=models.CharField(default='날짜', max_length=10),
        ),
        migrations.AlterField(
            model_name='gall',
            name='summ',
            field=models.CharField(default='설명', max_length=100),
        ),
        migrations.AlterField(
            model_name='gall',
            name='title',
            field=models.CharField(default='제목', max_length=50),
        ),
    ]
