# Generated by Django 3.0.6 on 2020-07-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s1app', '0005_auto_20200707_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gall',
            name='summ',
            field=models.TextField(default='설명'),
        ),
    ]
