# Generated by Django 3.0.6 on 2020-05-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('perefer', models.IntegerField()),
                ('live', models.BooleanField()),
                ('follower', models.IntegerField()),
                ('link1', models.TextField(blank=True)),
                ('link2', models.TextField(blank=True)),
            ],
        ),
    ]
