# Generated by Django 3.0.6 on 2020-05-18 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cd5app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtube',
            old_name='perefer',
            new_name='prefer',
        ),
    ]
