# Generated by Django 3.0.6 on 2020-05-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cd5app', '0002_auto_20200518_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube',
            name='link3',
            field=models.TextField(blank=True),
        ),
    ]
